# Site metadata
site_name: Premiere Pro C++ SDK Guide
site_url: https://ppro-plugins.docsforadobe.dev/
repo_url: https://github.com/docsforadobe/premiere-plugin-guide/
repo_name: "premiere-plugin-guide"

# Customize navigation
nav:
    - Home: index.md
    - History:
        - Version History: history.md
    - Introduction:
        - Introduction: intro/intro.md
        - What Premiere Plug-Ins Do: introwhat-premiere-plugins-do.md)
        - SDK Audience: intro/sdk-audience.md
        - Whats New: intro/whats-new.md
        - Where Do I Start: intro/where-do-i-start.md
        - Document Overview: intro/document-overview.md
        - Getting Support and Providing Feedback: introgetting-support.md)
        - Premiere Pro Plug-In Types: intropremiere-pro-plugin-types.md)
        - Sample Projects: intro/sample-projects.md
        - Debugging Plug-Ins: intro/debugging-plugins.md
        - Load Em Up: intro/load-em-up.md
        - Plug In Installation: intro/plugin-installationmd)
        - Localization: intro/localization.md
        - Best Practices: intro/best-practices.md
    - Resources:
        - Resources: resources/resources.md
        - Plug-In Property Lists (PiPL) Resource: resources/pipl-resource.md
        - IMPT Resource: resources/impt-resource.md
    - Universals:
        - Universals: universals/universals.md
        - Time: universals/time.md
        - Video Frames: universals/video-frames.md
        - Pixel Formats And Color Spaces: universalspixel-formats-and-color-spaces.md)
        - Pixel Aspect Ratio: universalspixel-aspect-ratio.md)
        - Fields: universals/fields.md
        - Audio: universals/audio.md
        - Memory Management: universals/memory-managementmd)
        - Basic Types Structures: universalsbasic-types-structures.md)
        - Suites: universals/suites.md
        - SweetPea Suites: universals/sweetpea-suites.md
        - Legacy Callback Suites: universalslegacy-callback-suites.md)
    - Hardware Integration:
        - Hardware: hardware/hardware.md
        - Hardware Integration Components: hardwarehardware-integration-components.md)
        - ClassID, Filetype and Subtype: hardwareclassid-filetype-subtype.md)
        - ClassData Functions: hardwareclassdata-functions.md)
    - Importers:
        - Importers: importers/importers.md
        - What’s New: importers/whats-new.md
        - Getting Started: importers/getting-started.md
        - Selector Table: importers/selector-table.md
        - Selector Descriptions: importersselector-descriptions.md)
        - Return Codes: importers/return-codes.md
        - Structures: importers/structures.md
        - Structure Descriptions: importersstructure-descriptions.md)
        - Suites: importers/suites.md
    - Export Controllers:
        - Export Controllers: export-controllersexport-controllers.md)
    - Exporters:
        - Exporters: exporters/exporters.md
        - Whats New: exporters/whats-new.md
        - Getting Started: exporters/getting-started.md
        - Selector Table: exporters/selector-table.md
        - Selector Descriptions: exportersselector-descriptions.md)
        - Return Codes: exporters/return-codes.md
        - Structures: exporters/structures.md
        - Structure Descriptions: exportersstructure-descriptions.md)
        - Suites: exporters/suites.md
        - Additional Details: exporters/additional-detailsmd)
    - Transmitters:
        - Transmitters: transmitters/transmitters.md
        - Transmitter Basics: transmitterstransmitter-basics.md)
        - tmModule Functions: transmitterstmModule-functions.md)
        - tmModule Structures: transmitterstmModule-structures.md)
        - Suites: transmitters/suites.md
    - Video Filters:
        - Video Filters: video-filters/video-filters.md
        - Whats New: video-filters/whats-new.md
        - Getting Started: video-filters/getting-startedmd)
        - Selector Table: video-filters/selector-table.md
        - Selector Descriptions: video-filtersselector-descriptions.md)
        - Return Codes: video-filters/return-codes.md
        - VideoRecord: video-filters/VideoRecord.md
        - Additional Details: video-filtersadditional-details.md)
    - GPU Effects & Transitions:
        - GPU Effects & Transitions: gpu-effects-transitions/gpu-effects-transitions.md
        - CUDA, OpenCL, Metal, or OpenGL?: gpu-effects-transitions/cuda-opencl-metal-openglmd)
        - What’s New in Premiere Pro 12.0?: gpu-effects-transitions/whats-new-in-ppro-12.md
        - What’s New in Premiere Pro CC 2015.4?: gpu-effects-transitions/whats-new-in-ppro-cc2015md)
        - What’s New in Premiere Pro CC 2014?: gpu-effects-transitions/whats-new-in-ppro-cc2014md)
        - Getting Started: gpu-effects-transitionsgetting-started.md)
        - PrGPUFilter Function Table: gpu-effects-transitions/PrGPUFilter-function-tablemd)
        - Function Descriptions: gpu-effects-transitionsfunction-descriptions.md)
        - Return Codes: gpu-effects-transitionsreturn-codes.md)
        - Structure Descriptions: gpu-effects-transitionsstructure-descriptions.md)
        - PrGPU SDK Macros: gpu-effects-transitionsPrGPU-SDK-macros.md)
        - Suites: gpu-effects-transitions/suites.md
    - AE Transition Extensions:
        - AE Transition Extensions: ae-transition-extensions/ae-transition-extensionsmd)
        - PF_TransitionSuite: ae-transition-extensionsPF_TransitionSuite.md)
        - Getting Started: ae-transition-extensionsgetting-started.md)
    - Control Surfaces:
        - Control Surfaces: control-surfacescontrol-surfaces.md)



# Do not touch below-- shared for all docs

copyright: All content is copyright Adobe Systems Incorporated.

extra:
    homepage: https://docsforadobe.dev

theme:
    name: material
    custom_dir: overrides
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - search.highlight
        - search.suggest
        - toc.follow
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: white
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

extra_css:
    # CSS shared between the whole org
    - https://docsforadobe.dev/_global/global.css
    - https://docsforadobe.dev/_global/global-syntax-highlight.css

    # CSS specific to this file
    - _static/extra.css

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        title: Page Contents
        permalink: true
        toc_depth: 3

plugins:
    - git-revision-date-localized
    - search:
        separator: '[\s\-,\.:!=\[\]()"/]+'

    # Note: print-site must be last!
    - print-site:
        add_cover_page: true
        add_print_site_banner: true
        cover_page_template: "overrides/templates/print_site_cover_page.tpl"
        print_page_title: "Offline Docs"
        print_site_banner_template: "overrides/templates/print_site_banner.tpl"
